#! usr/bin/env php
<?php

namespace AntiPatterns\SingletonsPool;

require_once 'vendor/autoload.php';

print (SingletonsPool::getInstance('First') === SingletonsPool::getInstance('Second')) ?: "SingletonsPool \n";
